In [9]:
import os
import sys

sys.path.append(os.path.abspath(".."))

from src.loaders import list_excel_sheets, load_excel_sheet
from src.parsers.qilt import find_all_qilt_sheets, parse_qilt_sheet
from src.types import ExcelSheet

In [10]:
gos_sheet = ExcelSheet(
    folder="QILT",
    data_source="QILT-2024-GOS",
    sheet_name="INDEX",
)

gos_excel_sheets = list_excel_sheets(gos_sheet.folder, gos_sheet.file_name)
gos_excel_sheet = gos_excel_sheets[1] # ! the test one

gos_test_sheet = ExcelSheet(
    folder=gos_sheet.folder,
    data_source=gos_sheet.data_source,
    sheet_name=gos_excel_sheet,
)

df = load_excel_sheet(gos_test_sheet.folder, gos_test_sheet.file_name, gos_test_sheet.sheet_name)
df

,"Employment (FTE, OE, LF, SAL) and study outcomes among all course levels from all provider types by provider type, 2023 - 2024",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,Back to INDEX,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Full-time employment,Overall employment,Labour force participation rate,Median annual full-time salaries ($),In full-time study (%)
3,Undergraduate 2023,Universities,79.4,89.1,92.6,"71,000",18.0
4,Undergraduate 2023,NUHEIs,65.3,83.4,89.3,"65,600",17.9
5,Undergraduate 2023,All institutions,79.0,88.9,92.5,"71,000",18.0
6,Undergraduate 2024,Universities,74.4,87.1,92.7,"75,000",17.9
7,Undergraduate 2024,NUHEIs,61.8,80.8,89.9,"70,000",19.4
8,Undergraduate 2024,All institutions,74.0,86.9,92.6,"75,000",17.9
9,Postgraduate coursework 2023,Universities,90.0,93.9,95.6,"97,000",7.1
10,Postgraduate coursework 2023,NUHEIs,92.7,94.3,95.6,"94,000",6.4
11,Postgraduate coursework 2023,All institutions,90.3,93.9,95.6,"96,600",7.1
12,Postgraduate coursework 2024,Universities,87.6,92.5,95.4,"101,000",7.4
13,Postgraduate coursework 2024,NUHEIs,91.9,93.6,95.3,"97,000",7.1
14,Postgraduate coursework 2024,All institutions,88.1,92.7,95.4,"100,000",7.3
15,Postgraduate research 2023,Universities,85.2,91.4,95.2,"100,000",6.9
16,Postgraduate research 2023,NUHEIs,NaN,NaN,NaN,NaN,NaN
17,Postgraduate research 2023,All institutions,85.3,91.4,95.2,"100,000",6.9
18,Postgraduate research 2024,Universities,82.8,90.5,95.1,"104,400",5.1
19,Postgraduate research 2024,NUHEIs,NaN,NaN,NaN,NaN,NaN
20,Postgraduate research 2024,All institutions,82.8,90.5,95.1,"104,400",5.1
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Column variables:,NaN,NaN,NaN,NaN,NaN,NaN
23,AVAILEMP,NaN,NaN,NaN,NaN,NaN,NaN
24,AVAILFT,NaN,NaN,NaN,NaN,NaN,NaN
25,FULLEMP,NaN,NaN,NaN,NaN,NaN,NaN
26,FURSTUD,NaN,NaN,NaN,NaN,NaN,NaN
27,GENEMP,NaN,NaN,NaN,NaN,NaN,NaN
28,SALARYA,NaN,NaN,NaN,NaN,NaN,NaN
29,TRIMSAL_ALL,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Column filters:,NaN,NaN,NaN,NaN,NaN,NaN
32,FTE: AVAILFT = 1,NaN,NaN,NaN,NaN,NaN,NaN
33,OE: AVAILEMP = 1,NaN,NaN,NaN,NaN,NaN,NaN
34,"SAL: FULLEMP = 1, TRIMSAL_ALL = 1",NaN,NaN,NaN,NaN,NaN,NaN
35,"FTS: FURSTUD = (1,2,5)",NaN,NaN,NaN,NaN,NaN,NaN
36,Data for all columns is filtered to: ANALYSIS ...,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Row variables:,NaN,NaN,NaN,NaN,NaN,NaN
39,HEPTYPE,NaN,NaN,NaN,NaN,NaN,NaN
40,YEAR,NaN,NaN,NaN,NaN,NaN,NaN
41,LEVEL,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,Row notes:,NaN,NaN,NaN,NaN,NaN,NaN
44,Universites: HEPTYPE = 1,NaN,NaN,NaN,NaN,NaN,NaN
45,NUHEIs: HEPTYPE = 2,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
gos_excel_sheets_df = find_all_qilt_sheets(gos_sheet.folder, gos_sheet.file_name)
gos_excel_sheets_df # ! use these results to inform what is chosen

,Sheet name,Sheet title
Sheet number,,
1,INDEX,GOS 2024 Tables and Figures
2,OVERALL_ALL_ALL_2Y_HEPTYPE,"Employment (FTE, OE, LF, SAL) and study outcom..."
3,EMP_UG_ALL_2Y_AREA,"Employment outcomes (FTE, OE, LF), 2023-2024 a..."
4,EMP_PGC_ALL_2Y_AREA,"Employment outcomes (FTE, OE, LF), 2023-2024 a..."
5,EMP_PGR_ALL_2Y_AREA,"Employment outcomes (FTE, OE, LF), 2023-2024 a..."
...,...,...
155,CRSPREP_PGC_ALL_1Y_AREA,Course prepared them well or very well for cur...
156,CRSPREP_PGR_ALL_1Y_AREA,Course prepared them well or very well for cur...
157,CRSPREP_UG_ALL_1Y_AREA_OCCF,Course prepared them well or very well for man...
158,CRSPREP_PGC_ALL_1Y_AREA_OCCF,Course prepared them well or very well for man...
159,CRSPREP_PGR_ALL_1Y_AREA_OCCF,Course prepared them well or very well for man...

In [12]:
gos_l_sheet = ExcelSheet(
    folder="QILT",
    data_source="QILT-2024-GOS-L", # ! data comparison, use ChatGPT to see what is common
    sheet_name="INDEX",
)
gos_l_excel_sheets_df = find_all_qilt_sheets(gos_l_sheet.folder, gos_l_sheet.file_name)
gos_l_excel_sheets_df

,Sheet name,Sheet title
Sheet number,,
1,INDEX,GOS-L 2024 Tables and Figures
2,FTE_UG_ALL_5Y,Short-term and medium-term domestic full-time ...
3,FTE_ALL_ALL_1Y_AREA,Short-term and medium-term full-time domestic ...
4,STMT_UG_ALL_3Y,Short-term and medium-term domestic employment...
5,STMT_PGC_ALL_3Y,Short-term and medium-term domestic employment...
...,...,...
158,STMT_PGR_ALL_1Y_SG,Short-term and medium-term domestic employment...
159,STMT_UG_ALL_1Y_E315,Short-term and medium-term domestic employment...
160,STMT_UG_ALL_1Y_HEPTYPE,Short-term and medium-term domestic employment...
161,STMT_UG_ALL_1Y_SG,Short-term and medium-term domestic employment...
162,SPOQ_ALL_ALL_1Y_E942,Occupation does not fully use skills or educat...

In [13]:
alternative_excel_sheet = gos_excel_sheets[4] # ! an alternative example

alternative_sheet = ExcelSheet(
    folder=gos_sheet.folder,
    data_source=gos_sheet.data_source,
    sheet_name=alternative_excel_sheet,
)
parsed_qilt_sheet = parse_qilt_sheet(alternative_sheet.folder, alternative_sheet.file_name, alternative_sheet.sheet_name)
parsed_qilt_sheet.table # ! a table, but yet to be cleaned

,AREA,Full-time employment 2023,Full-time employment 2024,Overall employment 2023,Overall employment 2024,Labour force participation rate 2023,Labour force participation rate 2024,30 years or under 2023,30 years or under 2024
0,Agriculture and environmental studies,83.7,82.6,96.2,89.0,97.2,99.0,29.6,31.7
1,Architecture and built environment,76.7,66.7,84.8,83.3,97.1,100.0,8.8,11.1
2,Business and management,85.8,83.3,94.2,90.0,95.9,92.7,12.2,13.7
3,Communications,80.0,72.4,88.6,90.0,92.1,93.0,21.1,20.9
4,Computing and information systems,86.3,75.7,85.9,85.4,97.5,95.3,20.0,22.1
5,Creative arts,83.0,73.4,92.9,87.9,93.9,91.8,15.0,24.0
6,Dentistry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Engineering,85.5,81.3,89.2,87.9,96.9,97.1,30.4,32.4
8,Health services and support,92.2,89.6,96.5,94.0,96.3,97.4,27.0,20.1
9,"Humanities, culture and social sciences",79.4,74.0,89.2,88.2,89.1,90.2,21.6,19.8
10,Law and paralegal studies,84.9,81.1,92.6,87.5,98.6,97.0,10.1,10.6
11,Medicine,86.0,90.7,90.3,93.7,97.2,94.7,29.6,27.3
12,Nursing,90.9,87.0,90.6,89.3,98.1,94.9,13.0,5.1
13,Pharmacy,83.3,89.5,87.5,90.9,100.0,97.8,50.0,48.9
14,Psychology,92.6,88.3,95.8,94.7,98.2,95.9,50.5,41.1
15,Rehabilitation,NaN,NaN,100.0,NaN,100.0,NaN,11.5,NaN
16,Science and mathematics,83.9,85.1,89.5,90.9,96.3,96.6,51.3,53.6
17,Social work,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Teacher education,87.4,84.2,94.1,91.4,94.4,98.2,4.7,2.7
19,"Tourism, hospitality, personal services, sport...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Veterinary science,NaN,NaN,92.3,NaN,100.0,NaN,42.3,NaN
21,Total,85.3,82.8,91.4,90.5,95.2,95.1,29.8,29.2
22,Standard deviation,10.5,8.8,7.2,4.7,3.2,4.3,16.0,13.9

In [14]:
from src.preparation.qilt import clean_qilt_parsed_sheet

cleaned_qilt_sheet = clean_qilt_parsed_sheet(parsed_qilt_sheet)
cleaned_qilt_sheet.table

,area,full_time_employment_2023,full_time_employment_2024,overall_employment_2023,overall_employment_2024,labour_force_participation_rate_2023,labour_force_participation_rate_2024,30_years_or_under_2023,30_years_or_under_2024
0,Agriculture and environmental studies,83.7,82.6,96.2,89.0,97.2,99.0,29.6,31.7
1,Architecture and built environment,76.7,66.7,84.8,83.3,97.1,100.0,8.8,11.1
2,Business and management,85.8,83.3,94.2,90.0,95.9,92.7,12.2,13.7
3,Communications,80.0,72.4,88.6,90.0,92.1,93.0,21.1,20.9
4,Computing and information systems,86.3,75.7,85.9,85.4,97.5,95.3,20.0,22.1
5,Creative arts,83.0,73.4,92.9,87.9,93.9,91.8,15.0,24.0
6,Dentistry,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
7,Engineering,85.5,81.3,89.2,87.9,96.9,97.1,30.4,32.4
8,Health services and support,92.2,89.6,96.5,94.0,96.3,97.4,27.0,20.1
9,"Humanities, culture and social sciences",79.4,74.0,89.2,88.2,89.1,90.2,21.6,19.8
10,Law and paralegal studies,84.9,81.1,92.6,87.5,98.6,97.0,10.1,10.6
11,Medicine,86.0,90.7,90.3,93.7,97.2,94.7,29.6,27.3
12,Nursing,90.9,87.0,90.6,89.3,98.1,94.9,13.0,5.1
13,Pharmacy,83.3,89.5,87.5,90.9,100.0,97.8,50.0,48.9
14,Psychology,92.6,88.3,95.8,94.7,98.2,95.9,50.5,41.1
15,Rehabilitation,<NA>,<NA>,100.0,<NA>,100.0,<NA>,11.5,<NA>
16,Science and mathematics,83.9,85.1,89.5,90.9,96.3,96.6,51.3,53.6
17,Social work,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
18,Teacher education,87.4,84.2,94.1,91.4,94.4,98.2,4.7,2.7
19,"Tourism, hospitality, personal services, sport...",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
20,Veterinary science,<NA>,<NA>,92.3,<NA>,100.0,<NA>,42.3,<NA>
21,Total,85.3,82.8,91.4,90.5,95.2,95.1,29.8,29.2
22,Standard deviation,10.5,8.8,7.2,4.7,3.2,4.3,16.0,13.9