In [1]:
import os
import sys

sys.path.append(os.path.abspath(".."))

from src.loaders import initialise_abs_sheet, load_excel_sheet # list_excel_sheets
from src.sources import RAW_SOURCE_DIRS
from src.parsers.abs import find_all_abs_sheets, parse_abs_sheet

In [2]:
RAW_SOURCE_DIRS

{'QILT': {'QILT-2024-GOS': '2024_GOS_National_Report_Tables.xlsx',
  'QILT-2024-GOS-L': '2024_GOS-L_National_Report_Tables.xlsx'},
 'ABS': {'SEW-T1-10': 'SEW25DC01 T1_T10.xlsx',
  'SEW-T11-12': 'SEW25DC02 T11_T12.xlsx',
  'SEW-T13-14': 'SEW25DC03 T13_T14.xlsx',
  'SEW-T15-17': 'SEW25DC04 T15_T17.xlsx',
  'SEW-T18-20': 'SEW25DC05 T18_T20.xlsx',
  'SEW-T21-23': 'SEW25DC06 T21_T23.xlsx',
  'SEW-T24': 'SEW25DC07 T24.xlsx',
  'SEW-T25-27': 'SEW25DC08 T25_T27.xlsx',
  'SEW-T28-32': 'SEW25DC09 T28_T32.xlsx',
  'SEW-T33-35': 'SEW25DC10 T33_T35.xlsx',
  'SEW-DIL': 'SEW25DIL.xlsx'},
 'ABS_EXTRAS': {}}

In [3]:
abs_sheet_1 = initialise_abs_sheet(1)

# abs_1_10_excel_sheets = list_excel_sheets("ABS", abs_sheet_1.file_name)

df = load_excel_sheet(abs_sheet_1.folder, abs_sheet_1.file_name, abs_sheet_1.sheet_name)
df

,"This worksheet contains estimates, proportions, relative standard error and margins of error for current study, by selected characteristics and state/territory, Persons aged 15 to 74 years. It ranges from cell A1 to J242.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Australian Bureau of Statistics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Table 1 Current study, by selected characteris...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Education and work, May 2025",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NSW,Vic.,Qld,SA,WA,Tas.,NT,ACT,Aust.
4,NaN,Estimate ('000),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
236,np Not available for publication,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
237,(a) 'Current study' includes school and non-sc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
238,(b) The estimates ('000) represent the number ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
239,(c) The proportions (%) provided here represen...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
240,© Commonwealth of Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
abs_excel_sheets_df = find_all_abs_sheets()
abs_excel_sheets_df

,Sheet name,Source file,Sheet title
Sheet number,,,
1,Table 1,SEW25DC01 T1_T10.xlsx,"Current study, by selected characteristics and..."
2,Table 2,SEW25DC01 T1_T10.xlsx,"Current study, by type of enrolment and state/..."
3,Table 3,SEW25DC01 T1_T10.xlsx,"School study, by selected characteristics by a..."
4,Table 4,SEW25DC01 T1_T10.xlsx,"Studying for a non-school qualification, by le..."
5,Table 5,SEW25DC01 T1_T10.xlsx,"Studying for a non-school qualification, by ma..."
6,Table 6,SEW25DC01 T1_T10.xlsx,"Studying for a non-school qualification, by le..."
7,Table 7,SEW25DC01 T1_T10.xlsx,"Studying for a non-school qualification, by le..."
8,Table 8,SEW25DC01 T1_T10.xlsx,"Enrolled or applied to enrol in study, by educ..."
9,Table 9,SEW25DC01 T1_T10.xlsx,"Apprentices and trainees, by selected characte..."
10,Table 10,SEW25DC01 T1_T10.xlsx,Applied for but not undertaking an apprentices...
11,Table 11,SEW25DC02 T11_T12.xlsx,"Current study, by age, by geography and sex, P..."
12,Table 12,SEW25DC02 T11_T12.xlsx,Current study at certificate III level or abov...
13,Table 13,SEW25DC03 T13_T14.xlsx,"Left school in previous year (2024), by select..."
14,Table 14,SEW25DC03 T13_T14.xlsx,Completion status of non-school qualification ...
15,Table 15,SEW25DC04 T15_T17.xlsx,"Engagement in employment and/or study, by sele..."
16,Table 16,SEW25DC04 T15_T17.xlsx,"Full engagement in employment and/or study, by..."
17,Table 17,SEW25DC04 T15_T17.xlsx,Full engagement in employment and/or study (ex...
18,Table 18,SEW25DC05 T18_T20.xlsx,"Attainment of year 12 or equivalent, by age, b..."
19,Table 19,SEW25DC05 T18_T20.xlsx,Attainment of year 12 or equivalent or non-sch...
20,Table 20,SEW25DC05 T18_T20.xlsx,Attainment of year 12 or equivalent or non-sch...
21,Table 21,SEW25DC06 T21_T23.xlsx,"Highest educational attainment, by state/terri..."
22,Table 22,SEW25DC06 T21_T23.xlsx,Highest educational attainment (non-school pri...
23,Table 23,SEW25DC06 T21_T23.xlsx,Highest educational attainment by age of young...
24,Table 24,SEW25DC07 T24.xlsx,"Non-school qualifications, by selected charact..."
25,Table 25,SEW25DC08 T25_T27.xlsx,"Non-school qualifications, by age, by geograph..."
26,Table 26,SEW25DC08 T25_T27.xlsx,"Non-school qualifications, by age and sex, 201..."
27,Table 27,SEW25DC08 T25_T27.xlsx,With or studying towards a non-school qualific...
28,Table 28,SEW25DC09 T28_T32.xlsx,"Highest non-school qualification, by level and..."
29,Table 29,SEW25DC09 T28_T32.xlsx,"Highest non-school qualification, by level and..."
30,Table 30,SEW25DC09 T28_T32.xlsx,"Highest non-school qualification, by level and..."
31,Table 31,SEW25DC09 T28_T32.xlsx,Employed persons highest non-school qualificat...
32,Table 32,SEW25DC09 T28_T32.xlsx,Employed persons skill level of occupation in ...
33,Table 33,SEW25DC10 T33_T35.xlsx,Highest non-school qualification at certificat...
34,Table 34,SEW25DC10 T33_T35.xlsx,Highest non-school qualification at bachelor d...
35,Table 35,SEW25DC10 T33_T35.xlsx,Highest non-school qualification at bachelor d...

In [5]:
parsed_abs_sheet = parse_abs_sheet(abs_sheet_1.folder, abs_sheet_1.file_name, abs_sheet_1.sheet_name)

parsed_abs_sheet.subtables[0].parsed_table

,measurement,measurement_label,subject,row_group,row_group_path,row_label,column_header,source_row,source_column,value,value_text,is_suppressed,is_not_available,column_header_1
0,estimate_count,Estimate ('000),Persons currently enrolled in study(b),Sex,Persons currently enrolled in study(b) | Sex,Male,NSW,9,2,503.3,503.3,False,False,NSW
1,estimate_count,Estimate ('000),Persons currently enrolled in study(b),Sex,Persons currently enrolled in study(b) | Sex,Male,Vic.,9,3,434.6,434.6,False,False,Vic.
2,estimate_count,Estimate ('000),Persons currently enrolled in study(b),Sex,Persons currently enrolled in study(b) | Sex,Male,Qld,9,4,304.4,304.4,False,False,Qld
3,estimate_count,Estimate ('000),Persons currently enrolled in study(b),Sex,Persons currently enrolled in study(b) | Sex,Male,SA,9,5,99.1,99.1,False,False,SA
4,estimate_count,Estimate ('000),Persons currently enrolled in study(b),Sex,Persons currently enrolled in study(b) | Sex,Male,WA,9,6,151.2,151.2,False,False,WA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,estimate_count,Estimate ('000),Persons currently enrolled in study(b),Labour force status,Persons currently enrolled in study(b) | Labou...,Total,WA,43,6,324.3,324.3,False,False,WA
257,estimate_count,Estimate ('000),Persons currently enrolled in study(b),Labour force status,Persons currently enrolled in study(b) | Labou...,Total,Tas.,43,7,60,60,False,False,Tas.
258,estimate_count,Estimate ('000),Persons currently enrolled in study(b),Labour force status,Persons currently enrolled in study(b) | Labou...,Total,NT,43,8,25.5,25.5,False,False,NT
259,estimate_count,Estimate ('000),Persons currently enrolled in study(b),Labour force status,Persons currently enrolled in study(b) | Labou...,Total,ACT,43,9,63.9,63.9,False,False,ACT
260,estimate_count,Estimate ('000),Persons currently enrolled in study(b),Labour force status,Persons currently enrolled in study(b) | Labou...,Total,Aust.,43,10,3293.8,3293.8,False,False,Aust.