In [1]:
import os
import sys

sys.path.append(os.path.abspath(".."))

from src.exports import export_chart_metadata, export_chart_tables, build_chart_metadata
from src.transform.build import build_chart_tables, prepare_all_sources, get_chart_table

In [2]:
prepared_sources = prepare_all_sources()
chart_tables = build_chart_tables(prepared_sources)
chart_metadata = build_chart_metadata(chart_tables, prepared_sources)
exported_chart_paths = export_chart_tables(chart_tables)
chart_metadata_path = export_chart_metadata(chart_metadata)

exported_chart_paths

{'chart_1a_degree_supply': PosixPath('/Users/niconapoli/Desktop/my stuff/Personal/Programming/homeless-graduate/data/processed/chart_1a_degree_supply.csv'),
 'chart_1b_skill_by_age': PosixPath('/Users/niconapoli/Desktop/my stuff/Personal/Programming/homeless-graduate/data/processed/chart_1b_skill_by_age.csv'),
 'chart_2_transition_window': PosixPath('/Users/niconapoli/Desktop/my stuff/Personal/Programming/homeless-graduate/data/processed/chart_2_transition_window.csv'),
 'chart_3_subgroup_bottleneck': PosixPath('/Users/niconapoli/Desktop/my stuff/Personal/Programming/homeless-graduate/data/processed/chart_3_subgroup_bottleneck.csv'),
 'chart_4_gap_shapes': PosixPath('/Users/niconapoli/Desktop/my stuff/Personal/Programming/homeless-graduate/data/processed/chart_4_gap_shapes.csv'),
 'chart_5_field_conversion': PosixPath('/Users/niconapoli/Desktop/my stuff/Personal/Programming/homeless-graduate/data/processed/chart_5_field_conversion.csv'),
 'chart_6_work_fit': PosixPath('/Users/niconapoli/Desktop/my stuff/Personal/Programming/homeless-graduate/data/processed/chart_6_work_fit.csv'),
 'chart_7_subgroup_comparator': PosixPath('/Users/niconapoli/Desktop/my stuff/Personal/Programming/homeless-graduate/data/processed/chart_7_subgroup_comparator.csv')}

In [3]:
chart_2_table = get_chart_table(2, chart_tables)
chart_2_table

    display_year             series_key  value_pct source_key  series_order
0           2020   gos_l_short_term_fte       73.0    gos_l_1             0
1           2020  gos_l_medium_term_fte       90.1    gos_l_1             1
2           2021   gos_l_short_term_fte       74.3    gos_l_1             0
3           2021  gos_l_medium_term_fte       88.9    gos_l_1             1
4           2022   gos_l_short_term_fte       73.6    gos_l_1             0
5           2022  gos_l_medium_term_fte       91.5    gos_l_1             1
6           2022     gos_short_term_fte       78.5     gos_21             2
7           2023   gos_l_short_term_fte       70.3    gos_l_1             0
8           2023  gos_l_medium_term_fte       91.7    gos_l_1             1
9           2023     gos_short_term_fte       79.0     gos_21             2
10          2024   gos_l_short_term_fte       71.1    gos_l_1             0
11          2024  gos_l_medium_term_fte       91.1    gos_l_1             1
12          2024     gos_short_term_fte       74.0     gos_21             2

In [4]:
chart_3_table = get_chart_table(3, chart_tables)
chart_3_table

,subgroup_dimension,gap_pp,lower_group,lower_group_pct,higher_group,higher_group_pct,source_key,sort_order
0,Home language,16.4,Other,58.1,English,74.5,gos_8,0
1,Study mode,9.3,Internal/Mixed,71.9,External,81.2,gos_8,1
2,Locality,8.9,Metro,71.7,Regional/Remote,80.6,gos_8,2
3,Indigenous,8.8,Non-Indigenous,73.9,Indigenous,82.7,gos_8,3
4,Disability,8.2,Disability reported,66.8,No disability reported,75.0,gos_8,4
5,Age group,7.7,30 and under,72.4,Over 30,80.1,gos_8,5
6,Gender,2.2,Male,72.7,Female,74.9,gos_5,6
7,First in family,1.7,Not first in family,73.4,First in family,75.1,gos_8,7
8,Socio-economic status,0.3,High,73.5,Low,73.8,gos_8,8

In [5]:
chart_4_table = get_chart_table(4, chart_tables)
chart_4_table

,subgroup_dimension,time_window,time_window_order,reference_group,reference_group_pct,comparison_group,comparison_group_pct,signed_gap_pp,source_key,sort_order
0,Home language,short_term,0,Other,58.1,English,74.5,16.4,gos_8,0
1,Home language,medium_term,1,Other,90.3,English,91.1,0.8,gos_l_160,0
2,Study mode,short_term,0,Internal/Mixed,71.9,External,81.2,9.3,gos_8,1
3,Study mode,medium_term,1,Internal/Mixed,91.0,External,91.5,0.5,gos_l_160,1
4,Locality,short_term,0,Metro,71.7,Regional/Remote,80.6,8.9,gos_8,2
5,Locality,medium_term,1,Metro,91.0,Regional/Remote,91.5,0.5,gos_l_160,2
6,Indigenous,short_term,0,Non-Indigenous,73.9,Indigenous,82.7,8.8,gos_8,3
7,Indigenous,medium_term,1,Non-Indigenous,91.1,Indigenous,90.9,-0.2,gos_l_160,3
8,Disability,short_term,0,Disability reported,66.8,No disability reported,75.0,8.2,gos_8,4
9,Disability,medium_term,1,Disability reported,86.3,No disability reported,91.6,5.3,gos_l_160,4
10,Age group,short_term,0,30 and under,72.4,Over 30,80.1,7.7,gos_8,5
11,Age group,medium_term,1,30 and under,91.3,Over 30,90.4,-0.9,gos_l_160,5
12,Gender,short_term,0,Male,72.7,Female,74.9,2.2,gos_8,6
13,Gender,medium_term,1,Male,90.9,Female,91.2,0.3,gos_l_160,6
14,First in family,short_term,0,Not first in family,73.4,First in family,75.1,1.7,gos_8,7
15,First in family,medium_term,1,Not first in family,88.0,First in family,88.6,0.6,gos_l_160,7
16,Socio-economic status,short_term,0,High,73.5,Low,73.8,0.3,gos_8,8
17,Socio-economic status,medium_term,1,High,91.5,Low,90.5,-1.0,gos_l_160,8

In [6]:
chart_5_table = get_chart_table(5, chart_tables)
chart_5_table

,study_area,short_term_fte_pct,medium_term_fte_pct,source_key
0,Agriculture and environmental studies,70.4,91.1,gos_l_6
1,Architecture and built environment,65.7,87.1,gos_l_6
2,Business and management,74.1,93.8,gos_l_6
3,Communications,55.9,84.4,gos_l_6
4,Computing and information systems,72.4,93.0,gos_l_6
5,Creative arts,49.6,81.3,gos_l_6
6,Dentistry,93.0,97.1,gos_l_6
7,Engineering,83.6,94.6,gos_l_6
8,Health services and support,74.3,92.8,gos_l_6
9,"Humanities, culture and social sciences",61.0,89.0,gos_l_6
10,Law and paralegal studies,73.6,95.8,gos_l_6
11,Medicine,88.6,99.3,gos_l_6
12,Nursing,77.6,93.3,gos_l_6
13,Pharmacy,96.2,95.6,gos_l_6
14,Psychology,63.7,88.5,gos_l_6
15,Rehabilitation,95.0,96.5,gos_l_6
16,Science and mathematics,63.3,88.8,gos_l_6
17,Social work,74.7,92.1,gos_l_6
18,Teacher education,81.8,95.7,gos_l_6
19,"Tourism, hospitality, personal services, sport...",65.5,84.4,gos_l_6
20,Veterinary science,85.4,90.0,gos_l_6

In [7]:
chart_6_table = get_chart_table(6, chart_tables)
chart_6_table

,study_area,fte_gain_pp,underutilisation_reduction_pp,fit_metric_key,employment_source_key,fit_source_key
0,Agriculture and environmental studies,20.7,14.6,skills_education_utilisation,gos_l_6,gos_l_26
1,Architecture and built environment,21.4,4.7,skills_education_utilisation,gos_l_6,gos_l_26
2,Business and management,19.7,7.7,skills_education_utilisation,gos_l_6,gos_l_26
3,Communications,28.5,3.0,skills_education_utilisation,gos_l_6,gos_l_26
4,Computing and information systems,20.6,6.7,skills_education_utilisation,gos_l_6,gos_l_26
5,Creative arts,31.7,1.4,skills_education_utilisation,gos_l_6,gos_l_26
6,Dentistry,4.1,5.4,skills_education_utilisation,gos_l_6,gos_l_26
7,Engineering,11.0,3.4,skills_education_utilisation,gos_l_6,gos_l_26
8,Health services and support,18.5,13.1,skills_education_utilisation,gos_l_6,gos_l_26
9,"Humanities, culture and social sciences",28.0,9.9,skills_education_utilisation,gos_l_6,gos_l_26
10,Law and paralegal studies,22.2,13.5,skills_education_utilisation,gos_l_6,gos_l_26
11,Medicine,10.7,0.4,skills_education_utilisation,gos_l_6,gos_l_26
12,Nursing,15.7,5.9,skills_education_utilisation,gos_l_6,gos_l_26
13,Pharmacy,-0.6,-4.2,skills_education_utilisation,gos_l_6,gos_l_26
14,Psychology,24.8,11.3,skills_education_utilisation,gos_l_6,gos_l_26
15,Rehabilitation,1.5,0.5,skills_education_utilisation,gos_l_6,gos_l_26
16,Science and mathematics,25.5,11.6,skills_education_utilisation,gos_l_6,gos_l_26
17,Social work,17.4,1.7,skills_education_utilisation,gos_l_6,gos_l_26
18,Teacher education,13.9,-0.1,skills_education_utilisation,gos_l_6,gos_l_26
19,Veterinary science,4.6,-7.6,skills_education_utilisation,gos_l_6,gos_l_26

In [8]:
chart_1b_table = get_chart_table(1.2, chart_tables)
chart_1b_table

,age_group,age_order,skill_level,skill_order,share_pct,source_key
0,15–24,0,Skill level 1 (highest),0,12.3,sew_32
1,15–24,0,Skill level 2,1,5.6,sew_32
2,15–24,0,Skill level 3,2,17.3,sew_32
3,15–24,0,Skill level 4,3,29.4,sew_32
4,15–24,0,Skill level 5 (lowest),4,35.1,sew_32
5,25–34,1,Skill level 1 (highest),0,37.8,sew_32
6,25–34,1,Skill level 2,1,12.2,sew_32
7,25–34,1,Skill level 3,2,13.7,sew_32
8,25–34,1,Skill level 4,3,24.6,sew_32
9,25–34,1,Skill level 5 (lowest),4,11.3,sew_32
10,35–44,2,Skill level 1 (highest),0,45.0,sew_32
11,35–44,2,Skill level 2,1,12.4,sew_32
12,35–44,2,Skill level 3,2,11.8,sew_32
13,35–44,2,Skill level 4,3,22.4,sew_32
14,35–44,2,Skill level 5 (lowest),4,8.0,sew_32
15,45–54,3,Skill level 1 (highest),0,42.9,sew_32
16,45–54,3,Skill level 2,1,13.0,sew_32
17,45–54,3,Skill level 3,2,11.0,sew_32
18,45–54,3,Skill level 4,3,23.1,sew_32
19,45–54,3,Skill level 5 (lowest),4,9.6,sew_32
20,55–64,4,Skill level 1 (highest),0,33.2,sew_32
21,55–64,4,Skill level 2,1,12.4,sew_32
22,55–64,4,Skill level 3,2,11.8,sew_32
23,55–64,4,Skill level 4,3,28.8,sew_32
24,55–64,4,Skill level 5 (lowest),4,13.5,sew_32
25,65–74,5,Skill level 1 (highest),0,36.9,sew_32
26,65–74,5,Skill level 2,1,12.1,sew_32
27,65–74,5,Skill level 3,2,11.0,sew_32
28,65–74,5,Skill level 4,3,25.8,sew_32
29,65–74,5,Skill level 5 (lowest),4,14.3,sew_32

In [9]:
chart_1a_table = get_chart_table(1.1, chart_tables)
chart_1a_table

,year,bachelor_degree_or_above_holders_population,bachelor_degree_or_above_holders_increase_pct,source_key
0,2016,4585900,0.0,sew_35
1,2017,4856400,5.9,sew_35
2,2018,5035900,9.8,sew_35
3,2019,5301500,15.6,sew_35
4,2020,5678600,23.8,sew_35
5,2021,5901900,28.7,sew_35
6,2022,6094300,32.9,sew_35
7,2023,6234900,36.0,sew_35
8,2024,6605200,44.0,sew_35
9,2025,6787200,48.0,sew_35

In [10]:
chart_7_table = get_chart_table(7, chart_tables)
chart_7_table

,selector_id,subgroup_dimension,time_window,time_window_order,reference_group,reference_group_pct,comparison_group,comparison_group_pct,signed_gap_pp,source_key,sort_order
0,home_language,Home language,short_term,0,Other,58.1,English,74.5,16.4,gos_8,0
1,home_language,Home language,medium_term,1,Other,90.3,English,91.1,0.8,gos_l_160,0
2,study_mode,Study mode,short_term,0,Internal/Mixed,71.9,External,81.2,9.3,gos_8,1
3,study_mode,Study mode,medium_term,1,Internal/Mixed,91.0,External,91.5,0.5,gos_l_160,1
4,locality,Locality,short_term,0,Metro,71.7,Regional/Remote,80.6,8.9,gos_8,2
5,locality,Locality,medium_term,1,Metro,91.0,Regional/Remote,91.5,0.5,gos_l_160,2
6,indigenous,Indigenous,short_term,0,Non-Indigenous,73.9,Indigenous,82.7,8.8,gos_8,3
7,indigenous,Indigenous,medium_term,1,Non-Indigenous,91.1,Indigenous,90.9,-0.2,gos_l_160,3
8,disability,Disability,short_term,0,Disability reported,66.8,No disability reported,75.0,8.2,gos_8,4
9,disability,Disability,medium_term,1,Disability reported,86.3,No disability reported,91.6,5.3,gos_l_160,4
10,age_group,Age group,short_term,0,30 and under,72.4,Over 30,80.1,7.7,gos_8,5
11,age_group,Age group,medium_term,1,30 and under,91.3,Over 30,90.4,-0.9,gos_l_160,5
12,gender,Gender,short_term,0,Male,72.7,Female,74.9,2.2,gos_8,6
13,gender,Gender,medium_term,1,Male,90.9,Female,91.2,0.3,gos_l_160,6
14,first_in_family,First in family,short_term,0,Not first in family,73.4,First in family,75.1,1.7,gos_8,7
15,first_in_family,First in family,medium_term,1,Not first in family,88.0,First in family,88.6,0.6,gos_l_160,7
16,socio_economic_status,Socio-economic status,short_term,0,High,73.5,Low,73.8,0.3,gos_8,8
17,socio_economic_status,Socio-economic status,medium_term,1,High,91.5,Low,90.5,-1.0,gos_l_160,8